package com.example.user.util;

import java.util.HashMap;
import java.util.Map;

public class FstpContants {


    public static Map<String, String> DEPRECIATION_AREAS_MAP = null;
    public static Map<String, String> FIXED_ASSETS_MAP = null;


    public static void setUpFixedAssetsMapping() {
        FIXED_ASSETS_MAP = new HashMap<>();
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.ASSET", "Asset");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.SUBNUMBER", "SubNumber");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003.WBS_ELEMENT_COST", "WbsElement");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003X.COSTCENTER", "CostCenter");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003X.RESP_CCTR", "CostCenterResponsible");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003X.FUND", "Fund");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003X.FUNC_AREA", "FunctionalArea");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003X.GRANT_NBR", "Grant");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003X.FUNC_AREA_LONG", "FunctionalAreaLong");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003X.FUNDS_CTR", "FundsCenter");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG004.EVALGROUP1", "EvaluationGroup1");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG004.EVALGROUP2", "EvaluationGroup2");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG004.EVALGROUP3", "EvaluationGroup3");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG004.EVALGROUP4", "EvaluationGroup4");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG004.EVALGROUP5", "EvaluationGroup5");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG004.INV_REASON", "ReasonForInvestment");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG004.ENVIR_INVEST", "ReasonForEnvironmentalInvestment");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003.TAXJURCODE", "TaxJurCode");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003.RL_EST_KEY", "RlEstKey");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003.RL_EST_KEY_EXT", "RlEstKeyExt");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003.BUDGET_PERIOD", "BudgetPeriod");
        FIXED_ASSETS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_FEGLG003.BUDGET_PERIOD_APC", "BudgetPeriodApc");
    }

    public  static void setUpDepreciationAreasMapping() {
        DEPRECIATION_AREAS_MAP = new HashMap<>();
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].AREA", "DepreciationAreas[*].RealDepreciationArea");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].DESCRIPT", "DepreciationAreas[*].ShortNameForDepreciationArea");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].DEACTIVATE", "DepreciationAreas[*].DepreciationAreaIsDeactivated");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].DEP_KEY", "DepreciationAreas[*].DepreciationKey");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].ULIFE_YRS", "DepreciationAreas[*].PlannedUsefulLifeInYears");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].ULIFE_PRDS", "DepreciationAreas[*].PlannedUsefulLifeInPeriods");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].EXP_ULIFE_YRS", "DepreciationAreas[*].ExpiredUsefulLifeInYears");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].EXP_ULIFE_PRDS", "DepreciationAreas[*].ExpiredUsefulLifeInPeriods");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].EXP_ULIFE_SDEP_YRS", "DepreciationAreas[*].ExpiredUsefulLifeInYearsFromSDep");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].EXP_ULIFE_SDEP_PRDS", "DepreciationAreas[*].ExpiredUsefulLifeInPeriodsFromSDep");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].ORIG_ULIFE_YRS", "DepreciationAreas[*].OriginalUsefulLifeInYears");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].ORIG_ULIFE_PRDS", "DepreciationAreas[*].OriginalUsefulLifeInPeriods");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].CHANGE_YR", "DepreciationAreas[*].DepreciationKeyForChangeoverYear");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].DEP_UNITS", "DepreciationAreas[*].NumberOfUnitsDepreciated");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].ODEP_START_DATE", "DepreciationAreas[*].DepreciationStartDate");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].SDEP_START_DATE", "DepreciationAreas[*].SpecialDepreciationStartDate");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].INTEREST_START_DATE", "DepreciationAreas[*].InterestCalculationStartDate");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].READINESS", "DepreciationAreas[*].OperatingReadinessDate");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].INDEX", "DepreciationAreas[*].IndexSeriesForReplacementValues");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].AGE_INDEX", "DepreciationAreas[*].IndexSeriesForReplacementValuesByAge");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].VAR_DEP_PORTION", "DepreciationAreas[*].VariableDepreciationPortion");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].SCRAPVALUE", "DepreciationAreas[*].AssetScrapValue");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].CURRENCY", "DepreciationAreas[*].CurrencyKey");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].CURRENCY_ISO", "DepreciationAreas[*].IsoCurrencyCode");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].NEG_VALUES", "DepreciationAreas[*].NegativeValuesAllowed");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].GRP_ASSET", "DepreciationAreas[*].GroupAsset");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].GRP_ASSET_SUBNO", "DepreciationAreas[*].GroupAssetSubnumber");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].ACQ_YR", "DepreciationAreas[*].AcquisitionYear");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].ACQ_PRD", "DepreciationAreas[*].AcquisitionMonth");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].SCRAPVALUE_PRCTG", "DepreciationAreas[*].ScrapValuePercentage");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].FROM_DATE", "DepreciationAreas[*].ValidityStartDate");
        DEPRECIATION_AREAS_MAP.put("IDOC.E1FIXEDASSET_CREATE.E1BP1022_DEP_AREAS[*].TO_DATE", "DepreciationAreas[*].ValidityEndDate");
    }
}
